### ISSUE TITLE
Footprint/player opacity discrepency

### ISSUE THREAD

**Issue by shinyjiggly** [wachunga/rmxp-dynamic-footprints#1]
When I set player's opacity to 0 via move event, I can still see the footprints left behind. This also occurs when player transparency is turned on.
As an aside, Squad movement (Enhanced squad movement in particular), despite being listed as compatible in another posting of the same script, still shows squad member footprints when they are set to hidden via the chosen switch. Yes, the script order is as expected.

Normally I would try and fix this myself, but the structure of this script makes it rather difficult to change starting opacity for a particular set of prints.

Yes, I know this script is a ton of years old, but I figure I might as well post this here for someone else to notice.

**Comment by shinyjiggly** [comment]
Update: I got some assistance from an RMXP wiz by the name of Jaiden and they managed to provide a quick-fix to this, to be placed on line 326:
```# Don't draw footprints for this character if it is invisible
   # Squad member check first
   if defined?(Game_Ally) && self.is_a?(Game_Ally)
     return if self.transparent == true
   end
   if self.opacity == 0
     return
   end
```
It seems to be working and hopefully this should be helpful to others who may be experiencing this problem.

**Comment by wachunga** [comment]
Thanks for taking the time to post the fix, @shinyjiggly. 👍
